export const packageSizes = [
    {
        id: 1,
        name: "Small - (Does not require taxi and coming from one store)",
        description: "Items such as groceries, fast food, pharmacy products, and small gadgets that fit in a backpack or plastic bag.",
        price: 0,
        backgroundColor: "#ECFDF5",
        borderColor: "#22C55E",
        badgeColor: "#22C55E",
        icon: "basket",
        iconColor: "#22C55E",
    },
    {
        id: 2,
        name: "Medium - (Require taxi and / or coming from different stores)",
        description: "Medium groceries and household items that are too large for a backpack and may need a taxi.",
        price: 100,
        backgroundColor: "#EFF6FF",
        borderColor: "#3B82F6",
        badgeColor: "#3B82F6",
        icon: "cube",
        iconColor: "#3B82F6",
    },
    {
        id: 3,
        name: "Large - (Pickup Truck / Van)",
        description: "Heavy or oversized packages that require a pickup truck or van.",
        price: 300,
        backgroundColor: "#FFF7ED",
        borderColor: "#F97316",
        badgeColor: "#F97316",
        icon: "archive",
        iconColor: "#F97316",
    },
    {
        id: 4,
        name: "Large (Pickup Truck / Van)",
        description: "Heavy or oversized packages that require a pickup truck or van.",
        price: 400,
        backgroundColor: "#FEF2F2",
        borderColor: "#EF4444",
        badgeColor: "#EF4444",
        icon: "car",
        iconColor: "#EF4444",
    },
];